name: Anthropic terms job

on:
  push:
    branches: [ main ]

  #schedule:
    #- cron: '0 1 * * *' # every night at 1 am UTC

jobs:
  anthropic-terms:
    runs-on: ubuntu-latest
    steps:
      - name: Check the terms and notify if necessary
        env:
          previous_terms: 2024-05-14
        run: |
          sudo apt-get install mailutils
          pip3 install setuptools --upgrade
          pip3 install git+https://github.com/adbar/htmldate.git
          current_terms="$(htmldate -u "https://www.anthropic.com/legal/commercial-terms")"
          echo "The current date of terms is $current_terms"
          echo "The previous date of terms is $previous_terms"
          if [ "$current_terms" == "$previous_terms" ];then
            echo "No change in terms"
          else
            echo "The terms at anthropic.com have been updated. Please check https://www.anthropic.com/legal/commercial-terms" | mail -s "Terms Updated at www.anthropic.com" ops@skyword.com
          fi
