name: Anthropic terms job

on:
  push:
    branches: [ main ]

  #schedule:
    #- cron: '0 1 * * *' # every night at 1 am UTC

jobs:
  anthropic-terms:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        env:
          previous_terms: 2024-05-13
        run: |
          pip3 install git+https://github.com/adbar/htmldate.git
          current_terms="$(htmldate -u "https://www.anthropic.com/legal/commercial-terms")"
          echo "The current date of terms is $current_terms"
          echo "The previous date of terms is $previous_terms"
          if (( $current_terms -ne $previous_terms ))
          then
                  echo "The terms at anthropic.com have been updated. Please check https://www.anthropic.com/legal/commercial-terms!" | mailx -s "Terms Updated at www.anthropic.com" shahrukh@skyword.com
          else
                  echo "No change in terms"
          fi
