name: Anthropic terms job

on:
  schedule:
    - cron: '0 1 * * *' # every night at 1 am UTC

jobs:
  anthropic-terms:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        run: pip3 install git+https://github.com/adbar/htmldate.git
      - name: Check out the repository to the runner
        run: htmldate -u "https://www.anthropic.com/legal/commercial-terms"
