name: Anthropic terms job

on:
  push:
    branches: [ main ]

  #schedule:
    #- cron: '0 1 * * *' # every night at 1 am UTC

jobs:
  anthropic-terms:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        env:
          TOKEN: ${{ secrets.ANTHROPIC_CURRENT_DATE }}
        run: |
          pip3 install git+https://github.com/adbar/htmldate.git
          current_terms="$(htmldate -u "https://www.anthropic.com/legal/commercial-terms")"
          echo "$current_terms"
          echo "$TOKEN"
          #anthropic_current_terms="$(curl -s $TOKEN)"
          #echo "$anthropic_current_terms"
