name: Google AI terms job

on:
  push:
    branches: [ main ]

  #schedule:
    #- cron: '0 1 * * *' # every night at 1 am UTC

jobs:
  google-ai:
    runs-on: ubuntu-latest
    steps:
      - name: Check the terms and notify if necessary
        env:
          previous_terms: Effective May 14, 2024
        run: |
          sudo apt-get install mailutils
          pip install trafilatura
          pip install lxml_html_clean
          current_terms="$(trafilatura -u "https://ai.google.dev/gemini-api/terms" | grep Effective)"
          echo "The current date of terms is $current_terms"
          echo "The previous date of terms is $previous_terms"
          if [ "$current_terms" == "$previous_terms" ];then
            echo "No change in terms"
          else
            echo "The terms at ai.google.dev have been updated. Please check https://https://ai.google.dev/gemini-api/terms" | mail -s "Terms Updated at ai.google.dev" shahrukh@skyword.com
          fi
