name: Nikto job

on:
  push:
    branches: [ main ]

  #schedule:
    #- cron: '0 1 * * *' # every night at 1 am UTC

jobs:
  nikto:
    runs-on: ubuntu-latest
    steps:
      - name: Run the scans and notify
        #env:
          #previous_terms: 2024-05-14
        run: |
          sudo apt-get install mailutils
          #sudo apt-get install nikto -y
          sudo apt-get install perl libnet-ssleay-perl openssl libauthen-pam-perl libio-pty-perl
          git clone https://github.com/sullo/nikto
          cd nikto/program
          #nikto
          #./nikto.pl --help
          #./nikto.pl -h https://create.skyword.com -output create.txt
          #./nikto.pl -h https://cargocdn.skyword.com -output create.txt
          #./nikto.pl -h https://cargocdn.skyword.com -o create.html -Format htm
          #./nikto.pl -h https://create.skyword.com -o create.html -Format nbe
          ./nikto.pl -h https://cargocdn.skyword.com -o create.nbe -Format nbe
          ./nikto.pl -h https://cargocdn.skyword.com -o create.csv -Format csv
          scan_results="$(cat create.csv)"
          #echo "$scan_results" | mail -s "Scan results of create.skyword.com" shahrukh@skyword.com
          #echo "$scan_results" | mail -s "Scan results of cargocdn.skyword.com" -a 'Content-Type: text/html; charset="UTF-8"' shahrukh@skyword.com
          echo "$scan_results" | mail -s "Scan results of create.skyword.com" -a 'Content-Type: text/html; charset="UTF-8"' shahrukh@skyword.com
